### PR TITLE
Simplify preflight

### PR DESCRIPTION
**Pull request by barryvdh**
Don't match the routes, just use the config.
Use the options response from Laravel.

### CODE REVIEW

**Comment by mlakerveld** [comment]
Hi Barry,

I'm curious to know why you have removed the route matching, as it seems like the ultimate solution.

We had some problems with it due to it checking the routes before all routes are merged (API routes were not checked yet).
So this change does fix our issue (although we fixed it by adding middleware infront of the HandlePreflight doing: `app('api.router.adapter')->dispatch($request, 'V1');`.

But if you have decided that no route checking is better, so be it.
I would like to ask if you could release this 0.10 release then. You have altered the composer.json, but in Composer the latest version is still 0.9

**Comment by barryvdh** [comment]
You should be able to use `0.10.x@dev` to test this release.

I found the route matching was giving some trouble, especially with `_method` calls and when it doesn't match it gives unclear errors.

**Comment by mlakerveld** [comment]
Thanks for the fast reply.

That's unfortunate. I'd rather not include a dev version in a production build, but this dev version only has that change so it'll be fine.

Thanks for making awesome packages!

**Comment by barryvdh** [comment]
Can you confirm th$ current dev version works? Then I'll tag it

**Comment by mlakerveld** [comment]
Just checked, everything seems to be working fine.

**Comment by barryvdh** [comment]
Tagged it

**Pull request merged**
