### PR TITLE
Only return proper CORS preflight headers if the OPTIONS request matches a route that's CORS-enabled

### LINKED ISSUE #91: Routes outside of the `cors` group are still accessible cross origin
I'm trying to figure out how this package actually only allows CORS for routes that use the `cors` middleware.

From what I can tell, the flow is something like:

- Incoming OPTIONS  request comes in for some route
- `HandlePreflight` adds the CORS headers _regardless of what the route is_
- The browser then makes the actual request, a POST request say
- If the `cors` middleware is present on that route, it checks to make sure it's coming from an allowed domain otherwise is 403s

What I don't understand, is what happens if the route is _not_ using the `cors` middleware? The allowed origins, methods, and headers were already returned based on the OPTIONS request, so the browser just makes the POST request to whatever URL and it just seems to go through?

The behavior I'm seeing in the network tab of various browsers is super confusing to be honest. If I have my route _outside_ of the CORS middleware, Chrome returns a 200 for the OPTIONS request, then a red response with no status code for the POST request, _but_ the code in that route is 100% executing, the browser is definitely making the request. Sometimes though Chrome returns a 204 instead of a red response, _but_ my AJAX success callbacks don't fire. Safari always returns a red response with no status code, and if memory serves correctly Firefox was doing the same thing.

What am I misunderstanding? How can I actually allow a CORS request to only work on a certain route with this package? It seems like the preflight response allows CORS for the _whole site_, but just doesn't add the right headers for the actual response _following_ the preflight, even though the code in that route still executes.

Brain is turning into goo trying to really get a grip on all this, hah...

### PR DESCRIPTION
**Pull request by adamwathan**
Resolves #91 for me locally, pull it down and give it a go :+1: 

`RouteCollection::match` will automatically throw a 404 if it matches no routes, so it doesn't need to be handled explicitly which is nice.

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks! I've merged, but made some tweaks in https://github.com/barryvdh/laravel-cors/commit/7dc8a4b44afecca5efce7344b584618ff4079028

- CORS middleware could have been added as global, so we need to ask the HTTP kernel for global middleware.
- If the matching fails, I just return the regular middleware flow. Not sure if this actually makes a difference, but this seems more appropriate. (If there are middlewares running after this one for example).
- Bumped to L5.1 minimum, because 5.0 doesn't have `hasMiddleware()`

Also, this probably doesn't work on Lumen, so I'll have to take a look how to fix it there also.

**Comment by barryvdh** [comment]
Oh and I've bumped these changes to 0.8, so to test, use `0.8.x@dev`

**Comment by adamwathan** [comment]
Great thanks for taking care of the stuff I missed @barryvdh, much appreciated! Definitely agree it makes sense to let the request run through the rest of the middleware if the match fails.

**Comment by barryvdh** [comment]
FYI, this has been tagged in 0.8.0 now.

**Pull request merged**
