### PR TITLE
Add config logic for Lumen to provider

### PR DESCRIPTION
**Pull request by dangreaves**
Removes config compatibility issues when used with Lumen. See #38.

### CODE REVIEW

**Comment by dragonfire1119** [comment]
I'm getting 
```
Class router does not exist
```

**Comment by dangreaves** [comment]
@dragonfire1119 yes this PR doesn't implement full support for Lumen. It merely fixes the config issue. Lumen doesn't use the Symfony router which the filters are aimed at. Middleware or some sort of filter that also supports nikic/fast-route will need to be implemented for Lumen.

**Comment by barryvdh** [comment]
Fixed in above commit.

**Comment by mallinus** [comment]
@barryvdh LumenServiceProvider not found. Seems like you forgot to add a tag for the latest commit. :)

Thanks for your work.

**Comment by barryvdh** [comment]
Yeah use the @dev version for now, will tag soonish.

**Pull request closed without merging**
